export const parks = [
  { id:"smokies", name:"Great Smoky Mountains", state:"Tennessee", lat:35.6118,lng:-83.4895, distance:373, category:["Mountains","Forest","Accessible"], tags:["misty","mountains","waterfalls","forest","moss","scenic drive"], match:96, color:"#697a55", image:"assets/smokies.jpg", description:"Blue ridgelines, old-growth forest, and waterfalls disappearing into morning mist." },
  { id:"mammoth", name:"Mammoth Cave", state:"Kentucky", lat:37.1869,lng:-86.1005, distance:177, category:["Forest","Accessible"], tags:["forest","cave","river","quiet","moss","underground"], match:89, color:"#4d684f", image:"assets/mammoth.jpg", description:"Wooded ridges and river valleys shelter the longest known cave system on Earth." },
  { id:"newriver", name:"New River Gorge", state:"West Virginia", lat:38.0709,lng:-81.0755, distance:382, category:["Mountains","Water","Forest"], tags:["river","gorge","forest","bridge","cliffs","waterfalls"], match:87, color:"#557779", image:"assets/newriver.jpg", description:"A whitewater river cuts through a deep Appalachian gorge beneath endless forest." },
  { id:"sleepingbear", name:"Sleeping Bear Dunes", state:"Michigan", lat:44.8826,lng:-86.0655, distance:340, category:["Water","Accessible"], tags:["lake","dunes","beach","sunset","blue water","sand"], match:84, color:"#7aa0ab", image:"assets/sleepingbear.jpg", description:"Monumental dunes rise over the deep blues of Lake Michigan." },
  { id:"shenandoah", name:"Shenandoah", state:"Virginia", lat:38.2928,lng:-78.6796, distance:487, category:["Mountains","Forest","Accessible"], tags:["mountains","misty","forest","sunrise","waterfalls","overlook"], match:82, color:"#7b735d", image:"assets/shenandoah.jpg", description:"A long ribbon of overlooks, waterfalls, and hazy Blue Ridge horizons." },
  { id:"isleroyale", name:"Isle Royale", state:"Michigan", lat:47.9959,lng:-88.9093, distance:575, category:["Water","Forest"], tags:["island","lake","wilderness","quiet","forest","kayak"], match:78, color:"#446c74", image:"assets/isleroyale.jpg", description:"Remote islands and cold clear coves reward travelers willing to leave the road behind." },
  { id:"badlands", name:"Badlands", state:"South Dakota", lat:43.8554,lng:-102.3397, distance:917, category:["Desert","Accessible"], tags:["desert","sunset","rock","badlands","prairie","dramatic"], match:75, color:"#b77c55", image:"assets/badlands.jpg", description:"Layered stone spires glow amber and rose above a vast mixed-grass prairie." },
  { id:"acadia", name:"Acadia", state:"Maine", lat:44.3386,lng:-68.2733, distance:1060, category:["Mountains","Water","Forest","Accessible"], tags:["ocean","mountains","rocky coast","sunrise","forest","lake"], match:73, color:"#426b78", image:"assets/acadia.jpg", description:"Granite summits meet the Atlantic along Maine’s wild, spruce-lined coast." }
];

export const locations = {
  "indianapolis, in": [39.7684,-86.1581], "chicago, il": [41.8781,-87.6298], "new york, ny": [40.7128,-74.006], "denver, co": [39.7392,-104.9903], "san francisco, ca": [37.7749,-122.4194]
};
