export const dogs = [
  {
    id: "sunny",
    name: "Sunny",
    age: "2 yrs",
    breed: "Golden retriever mix",
    distance: 1.8,
    lat: 39.8351,
    lng: -86.1877,
    shelter: "Indy Humane",
    neighborhood: "North Michigan Rd",
    type: "adopt",
    vibe: 96,
    photo: "0 0",
    tags: ["Affectionate", "Goofy", "Trail buddy"],
    bio: "Sunny has never met a stranger. He loves long walks, soft toys, and leaning his whole body into a good scratch.",
    fee: "$175 adoption fee",
  },
  {
    id: "pepper",
    name: "Pepper",
    age: "3 yrs",
    breed: "Border collie mix",
    distance: 2.4,
    lat: 39.7795,
    lng: -86.1358,
    shelter: "FACE Low-Cost Animal Clinic",
    neighborhood: "Mass Ave",
    type: "adopt",
    vibe: 92,
    photo: "50% 0",
    tags: ["Smart", "Playful", "Quick learner"],
    bio: "Pepper is an eager, clever companion who already knows sit, stay, and exactly where you keep the treats.",
    fee: "$150 adoption fee",
  },
  {
    id: "miso",
    name: "Miso",
    age: "1 yr",
    breed: "Terrier mix",
    distance: 3.1,
    lat: 39.7526,
    lng: -86.1401,
    shelter: "Foster home",
    neighborhood: "Fountain Square",
    type: "pet",
    vibe: 89,
    photo: "100% 0",
    tags: ["Gentle", "Cuddly", "Small but mighty"],
    bio: "Miso is being fostered nearby and loves meeting new people. Her foster family welcomes calm weekend playdates.",
    fee: "Free supervised visit",
  },
  {
    id: "cocoa",
    name: "Cocoa",
    age: "4 yrs",
    breed: "Chocolate lab mix",
    distance: 4.6,
    lat: 39.7739,
    lng: -86.1034,
    shelter: "IndyHumane Downtown",
    neighborhood: "Near Eastside",
    type: "adopt",
    vibe: 87,
    photo: "0 100%",
    tags: ["Loyal", "Foodie", "Fetch pro"],
    bio: "Cocoa is happiest with a tennis ball nearby. She is house-trained, people-focused, and ready for a steady routine.",
    fee: "$125 adoption fee",
  },
  {
    id: "bruno",
    name: "Bruno",
    age: "2 yrs",
    breed: "Boxer mix",
    distance: 5.2,
    lat: 39.7212,
    lng: -86.0886,
    shelter: "Southside Animal Shelter",
    neighborhood: "Beech Grove",
    type: "adopt",
    vibe: 84,
    photo: "50% 100%",
    tags: ["Bouncy", "Social", "Big heart"],
    bio: "Bruno is a joyful, wiggly optimist. He would love an active home and a couch big enough for afternoon naps.",
    fee: "$175 adoption fee",
  },
  {
    id: "archie",
    name: "Archie",
    age: "9 yrs",
    breed: "Senior mixed breed",
    distance: 6.7,
    lat: 39.8696,
    lng: -86.1411,
    shelter: "Forever Above Ground",
    neighborhood: "Broad Ripple",
    type: "pet",
    vibe: 81,
    photo: "100% 100%",
    tags: ["Mellow", "Sweet", "Professional napper"],
    bio: "Archie is a gentle senior who enjoys slow strolls and sunny porches. His rescue arranges low-key community visits.",
    fee: "Free supervised visit",
  },
  {
    id: "luna", name: "Luna", age: "2 yrs", breed: "Siberian husky", distance: 3.3,
    lat: 39.8134, lng: -86.1581, shelter: "Friends of Indianapolis Dogs", neighborhood: "Mapleton–Fall Creek",
    type: "adopt", vibe: 95, photo: "0 0", image: "assets/dogs/luna.jpg",
    tags: ["Adventurous", "Chatty", "Snow fan"],
    bio: "Luna is an expressive trail companion with bright energy and a soft spot for frozen treats.",
    fee: "$200 adoption fee", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "ollie", name: "Ollie", age: "4 yrs", breed: "Beagle", distance: 4.2,
    lat: 39.7711, lng: -86.2147, shelter: "Speedway Animal Rescue", neighborhood: "Speedway",
    type: "adopt", vibe: 93, photo: "0 0", image: "assets/dogs/ollie.jpg",
    tags: ["Curious", "Snack expert", "Easygoing"],
    bio: "Ollie follows his nose and then follows you. He loves sniffy walks, couch naps, and patient people.",
    fee: "$150 adoption fee", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "winnie", name: "Winnie", age: "3 yrs", breed: "Dalmatian", distance: 4.0,
    lat: 39.7350, lng: -86.1740, shelter: "Community playdate host", neighborhood: "Garfield Park",
    type: "pet", vibe: 91, photo: "0 0", image: "assets/dogs/winnie.jpg",
    tags: ["Social", "Runner", "Polka-dot pal"],
    bio: "Winnie is a confident neighborhood regular whose family welcomes friendly weekend walks and park visits.",
    fee: "Free supervised visit", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "theo", name: "Theo", age: "5 yrs", breed: "Pug", distance: 5.5,
    lat: 39.8540, lng: -86.1520, shelter: "Helping Paws Indy", neighborhood: "Meridian–Kessler",
    type: "adopt", vibe: 90, photo: "0 0", image: "assets/dogs/theo.jpg",
    tags: ["Comedian", "Cuddly", "Lap dog"],
    bio: "Theo brings serious charm to short walks. He is happiest near people and always ready for a cozy afternoon.",
    fee: "$175 adoption fee", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "nova", name: "Nova", age: "2 yrs", breed: "Samoyed", distance: 4.8,
    lat: 39.7681, lng: -86.0918, shelter: "Irvington foster family", neighborhood: "Irvington",
    type: "pet", vibe: 89, photo: "0 0", image: "assets/dogs/nova.jpg",
    tags: ["Friendly", "Fluffy", "Photo ready"],
    bio: "Nova is a cloud with paws. Her foster family hosts short meet-and-greets while she practices calm greetings.",
    fee: "Free supervised visit", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "teddy", name: "Teddy", age: "3 yrs", breed: "Shiba inu", distance: 2.9,
    lat: 39.8015, lng: -86.1200, shelter: "Indy Neighborhood Cats & Dogs", neighborhood: "Near Northside",
    type: "adopt", vibe: 88, photo: "0 0", image: "assets/dogs/teddy.jpg",
    tags: ["Independent", "Clever", "Quiet"],
    bio: "Teddy likes to take his time, observe the room, and choose his people person. Earning his trust is the best reward.",
    fee: "$225 adoption fee", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "rosie", name: "Rosie", age: "1 yr", breed: "Chihuahua mix", distance: 8.7,
    lat: 39.6909, lng: -86.1363, shelter: "Southside foster network", neighborhood: "Southport",
    type: "adopt", vibe: 87, photo: "0 0", image: "assets/dogs/rosie.jpg",
    tags: ["Tiny", "Brave", "Velcro dog"],
    bio: "Rosie is pocket-sized and full of opinions. Once she knows you, she wants to be part of every plan.",
    fee: "$185 adoption fee", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "jasper", name: "Jasper", age: "6 yrs", breed: "Poodle mix", distance: 10.2,
    lat: 39.8845, lng: -86.0563, shelter: "Northside playdate host", neighborhood: "Castleton",
    type: "pet", vibe: 86, photo: "0 0", image: "assets/dogs/jasper.jpg",
    tags: ["Gentle", "Polite", "Puzzle fan"],
    bio: "Jasper is a mellow host who enjoys meeting calm visitors, solving treat puzzles, and showing off his favorite park.",
    fee: "Free supervised visit", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "scout", name: "Scout", age: "2 yrs", breed: "Pembroke corgi", distance: 9.6,
    lat: 39.8970, lng: -86.1766, shelter: "Hamilton County Humane", neighborhood: "Home Place",
    type: "adopt", vibe: 85, photo: "0 0", image: "assets/dogs/scout.jpg",
    tags: ["Bright", "Busy", "Low rider"],
    bio: "Scout is short, speedy, and very serious about games. He would thrive with structure and plenty to do.",
    fee: "$250 adoption fee", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "sasha", name: "Sasha", age: "3 yrs", breed: "Belgian malinois", distance: 4.5,
    lat: 39.7462, lng: -86.2025, shelter: "Working Dog Rescue Indy", neighborhood: "West Indianapolis",
    type: "adopt", vibe: 84, photo: "0 0", image: "assets/dogs/sasha.jpg",
    tags: ["Athletic", "Focused", "Trainable"],
    bio: "Sasha is a brilliant athlete looking for an experienced home that will make training and enrichment a daily habit.",
    fee: "$200 adoption fee", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "noodle", name: "Noodle", age: "2 yrs", breed: "Pomeranian", distance: 7.1,
    lat: 39.8305, lng: -86.2442, shelter: "Community playdate host", neighborhood: "Pike Township",
    type: "pet", vibe: 83, photo: "0 0", image: "assets/dogs/noodle.jpg",
    tags: ["Bubbly", "Fluffy", "People watcher"],
    bio: "Noodle is a cheerful little extrovert whose person welcomes gentle visitors for patio hangs and short walks.",
    fee: "Free supervised visit", source_url: "https://dog.ceo/dog-api/",
  },
  {
    id: "louie", name: "Louie", age: "7 yrs", breed: "Basset hound", distance: 9.8,
    lat: 39.7070, lng: -86.2500, shelter: "Hoosier Hound Rescue", neighborhood: "Decatur Township",
    type: "adopt", vibe: 82, photo: "0 0", image: "assets/dogs/louie.jpg",
    tags: ["Mellow", "Soulful", "Scent detective"],
    bio: "Louie moves at his own thoughtful pace. He wants a soft bed, unhurried walks, and a family who appreciates good ears.",
    fee: "$125 adoption fee", source_url: "https://dog.ceo/dog-api/",
  },
];

export const cats = [
  {
    id: "cat-00026be097dd6e3c", name: "Iris", age: "10 yrs", breed: "Korat", distance: 1.1,
    lat: 39.766359, lng: -86.177982, shelter: "Central Indiana Cat Friends", neighborhood: "Downtown",
    type: "pet", vibe: 79, image: "assets/cats/generated/00026be097dd6e3c.webp",
    tags: ["Chatty", "Purr machine", "Cuddly"],
    bio: "Iris is a chatty, cuddly companion who loves cozy company and the best sunny window in the room.",
    fee: "Free supervised visit", source_url: "https://cataas.com/cat/JgWaCxZ0sz3yZ2Xz", source: "Cataas", demo: true,
  },
  {
    id: "cat-002cd071b1c4b1b8", name: "Ruby", age: "3 yrs", breed: "Maine Coon", distance: 1.1,
    lat: 39.772961, lng: -86.137773, shelter: "Nine Lives Indy", neighborhood: "Downtown",
    type: "adopt", vibe: 86, image: "assets/cats/generated/002cd071b1c4b1b8.webp",
    tags: ["Curious", "Toy hunter", "Goofy"],
    bio: "Ruby is a curious Maine Coon with comic timing, excellent toy-hunting skills, and plenty of affection to share.",
    fee: "$200 adoption fee", source_url: "https://cataas.com/cat/Ik8OqCzK3TIwjuaY", source: "Cataas", demo: true,
  },
  {
    id: "cat-00350208e962983d", name: "Casper", age: "12 yrs", breed: "Manx", distance: 9.1,
    lat: 39.87118, lng: -86.05175, shelter: "Paws Around Town", neighborhood: "Castleton",
    type: "adopt", vibe: 81, image: "assets/cats/generated/00350208e962983d.webp",
    tags: ["Window watcher", "Calm", "Chatty"],
    bio: "Casper is a calm senior who enjoys quiet conversations, window watching, and unhurried afternoons.",
    fee: "$125 adoption fee", source_url: "https://cataas.com/cat/LhYFWCG2rIhbUHD2", source: "Cataas", demo: true,
  },
  {
    id: "cat-005b07abc92a1607", name: "Waffles", age: "14 yrs", breed: "Burmese", distance: 3.9,
    lat: 39.772179, lng: -86.230438, shelter: "Paws Around Town", neighborhood: "Speedway",
    type: "adopt", vibe: 86, image: "assets/cats/generated/005b07abc92a1607.webp",
    tags: ["Foodie", "Mellow", "Friendly"],
    bio: "Waffles is a mellow Burmese foodie looking for a soft landing, regular snacks, and a friendly lap.",
    fee: "$100 adoption fee", source_url: "https://cataas.com/cat/g2fCWbQCuhPXDAnI", source: "Cataas", demo: true,
  },
  {
    id: "cat-008394bab0c4332f", name: "Sage", age: "4 yrs", breed: "Ocicat", distance: 2.7,
    lat: 39.752293, lng: -86.11082, shelter: "Central Indiana Cat Friends", neighborhood: "Irvington",
    type: "adopt", vibe: 75, image: "assets/cats/generated/008394bab0c4332f.webp",
    tags: ["Easygoing", "Loyal", "Foodie"],
    bio: "Sage is an easygoing Ocicat who warms up over treats and becomes a loyal little shadow.",
    fee: "$125 adoption fee", source_url: "https://cataas.com/cat/eyUdDf7M33hGJUWy", source: "Cataas", demo: true,
  },
  {
    id: "cat-0089b818fb127e1d", name: "Echo", age: "11 yrs", breed: "Exotic Shorthair", distance: 13,
    lat: 39.69095, lng: -86.381329, shelter: "Nine Lives Indy", neighborhood: "Plainfield",
    type: "adopt", vibe: 76, image: "assets/cats/generated/0089b818fb127e1d.webp",
    tags: ["Toy hunter", "Sweet", "Chatty"],
    bio: "Echo is a sweet, talkative senior who still takes every feather toy challenge very seriously.",
    fee: "$200 adoption fee", source_url: "https://cdn2.thecatapi.com/images/MTUyODg0OQ.jpg", source: "The Cat API", demo: true,
  },
  {
    id: "cat-00e8ac5dd66f54a8", name: "Ruby", age: "7 yrs", breed: "Calico", distance: 10.6,
    lat: 39.889432, lng: -86.035414, shelter: "Circle City Cat Collective", neighborhood: "Castleton",
    type: "adopt", vibe: 93, image: "assets/cats/generated/00e8ac5dd66f54a8.webp",
    tags: ["Loyal", "Sunbeam seeker", "Social"],
    bio: "Ruby is a social Calico who follows the sun across the room and keeps close to her favorite people.",
    fee: "$225 adoption fee", source_url: "https://cataas.com/cat/d9p2AdRYplbYTcvH", source: "Cataas", demo: true,
  },
  {
    id: "cat-00f60a688274a80f", name: "Ash", age: "8 yrs", breed: "Birman", distance: 3.2,
    lat: 39.765317, lng: -86.218097, shelter: "Nine Lives Indy", neighborhood: "Speedway",
    type: "adopt", vibe: 87, image: "assets/cats/generated/00f60a688274a80f.webp",
    tags: ["Loyal", "Foodie", "Clever"],
    bio: "Ash is a clever Birman who learns routines quickly and never misses the sound of a treat bag.",
    fee: "$100 adoption fee", source_url: "https://cataas.com/cat/1N2AH31jiY6N9TYc", source: "Cataas", demo: true,
  },
  {
    id: "cat-00ffc5e99f0dbde0", name: "Luna", age: "5 yrs", breed: "British Shorthair", distance: 9.5,
    lat: 39.90309, lng: -86.125346, shelter: "Indy Second Chance Cats", neighborhood: "Nora",
    type: "adopt", vibe: 75, image: "assets/cats/generated/00ffc5e99f0dbde0.webp",
    tags: ["Foodie", "Goofy", "Sunbeam seeker"],
    bio: "Luna is a goofy British Shorthair who can turn any sunbeam or cardboard box into an event.",
    fee: "$200 adoption fee", source_url: "https://cataas.com/cat/OcCyCN1wBhrCZAvP", source: "Cataas", demo: true,
  },
  {
    id: "cat-011d05a553152302", name: "Iris", age: "8 yrs", breed: "Tortoiseshell", distance: 14.1,
    lat: 39.958067, lng: -86.258034, shelter: "Indy Second Chance Cats", neighborhood: "Zionsville",
    type: "adopt", vibe: 86, image: "assets/cats/generated/011d05a553152302.webp",
    tags: ["Blanket burrower", "Bright", "Cuddly"],
    bio: "Iris is a bright Tortoiseshell who specializes in blanket forts and close-range cuddling.",
    fee: "$225 adoption fee", source_url: "https://cataas.com/cat/QkOfoBnDmxLH5cVJ", source: "Cataas", demo: true,
  },
  {
    id: "cat-01348b74ffcd8bcf", name: "Nala", age: "4 yrs", breed: "European Shorthair", distance: 9.8,
    lat: 39.878056, lng: -86.03985, shelter: "Indy Second Chance Cats", neighborhood: "Castleton",
    type: "pet", vibe: 91, image: "assets/cats/generated/01348b74ffcd8bcf.webp",
    tags: ["Cuddly", "Mellow", "Calm"],
    bio: "Nala is a mellow European Shorthair whose family welcomes calm visitors for supervised cuddle sessions.",
    fee: "Free supervised visit", source_url: "https://cataas.com/cat/zXL8RnmFrbYUiFkk", source: "Cataas", demo: true,
  },
  {
    id: "cat-01555d82ca0aa34f", name: "Marbles", age: "10 yrs", breed: "Somali", distance: 1.9,
    lat: 39.746336, lng: -86.137795, shelter: "Nine Lives Indy", neighborhood: "Fountain Square",
    type: "adopt", vibe: 93, image: "assets/cats/generated/01555d82ca0aa34f.webp",
    tags: ["Affectionate", "Blanket burrower", "Lap cat"],
    bio: "Marbles is an affectionate Somali with impeccable lap-cat instincts and a love of blanket forts.",
    fee: "$100 adoption fee", source_url: "https://cataas.com/cat/zMRpe7y2vpgxPum9", source: "Cataas", demo: true,
  },
];

export const matches = [
  { breed: "Golden retriever mix", score: 96, dogId: "sunny", reason: "warm, curious & impossible not to like" },
  { breed: "Border collie mix", score: 93, dogId: "pepper", reason: "bright-eyed, clever & ready for anything" },
  { breed: "Terrier mix", score: 91, dogId: "miso", reason: "spirited, expressive & secretly very cuddly" },
];
